version: '3.1'

services:
  codrr_pg:
    image: postgres:15.1
    container_name: codrr_pg
    restart: always
    environment:
      POSTGRES_DB: nube
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 210302
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-nube
    ports:
      - 3000:3000
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NODE_ENV: production
    depends_on:
      codrr_pg:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env # Montar el archivo .env dentro del contenedor
    restart: always

volumes:
  db-data: {} 