version: '3.1'

services:
  codrr_pg:
    image: postgres:15.1
    container_name: codrr_pg
    restart: always
    environment:
      POSTGRES_DB: nube
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dummypass
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 10s
    # Incecesario 
    # volumes:
    #  - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-nube
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    depends_on:
      codrr_pg:
        condition: service_healthy
        restart: true
    # Inecesario ya se define en el dockerfile
    # command: npm run start:dev

volumes:
  db-data: {} 