version: '3.1'

services:
  codrr_pg:
    image: postgres:15.1
    container_name: codrr_pg
    restart: always
    environment:
      POSTGRES_DB: nube
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dummypass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-nube
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    depends_on:
      - codrr_pg
    command: npm run start:dev