version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - sqlite
    environment:
      - NODE_ENV=production

  sqlite:
    image: nouchka/sqlite3:latest
    volumes:
      - ./database:/var/lib/sqlite/data
    environment:
      - SQLITE_USER=sqlite
      - SQLITE_PASSWORD=sqlite
      - SQLITE_DB=sqlite