### solo devuelve status
GET http://localhost:3000/status
content-type: application/json

### solo crea directorios
POST http://localhost:3000/directories
content-type: application/json

{
  "name":"Paola Ascanio",
  "emails": [
           "pao4@gmail.com",
           "armando@gmail.com"
   ] 
}


### solo retorna directorios
GET http://localhost:3000/directories
content-type: application/json

### solo retorna un directorio por ID
GET http://localhost:3000/directories/1
content-type: application/json

### solo elimina un directorio
DELETE http://localhost:3000/directories/2
content-type: application/json

### Solo actualiza parcialmente a un directorio

PATCH http://localhost:3000/directories/1
content-type: application/json

{
  "name": "Armando Lopez"
}


### Solo actualiza a un directorio

PUT http://localhost:3000/directories/1
content-type: application/json

{
  "name": "pabloLopez",
    "emails": [
           "Aja@gmail.com",
           "arm@gmail.com"
   ] 
}