### solo devuelve status
GET http://localhost:3000/status
content-type: application/json

### solo crea directorios
POST http://localhost:3000/directories
content-type: application/json

{
  "name":"andres lopez",
  "emails": [
           "pao@gmail.com",
           "armando@gmail.com"
   ] 
}


### solo retorna directorios
GET http://localhost:3000/directories
content-type: application/json